// SPDX-License-Identifier: MIT
pragma experimental ABIEncoderV2;
pragma solidity >=0.6.3 <0.8.0;


import "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/utils/StringsUpgradeable.sol";

contract Graphic is OwnableUpgradeable {


    // Audio Fles Contract:

    // File number: 1 
    // Title: Breaking the Chain
    // Album: Living an Impossible Dream
    // Website: https://QuantumIndigo.org
    // IPFS URL: (IPFS URL)
    // Comment: The World's First Decentralised Media Arts Collective.
    // Copyright: 2020 QMP (GnuPG ID FFE28038)
    // Submission Date: [DD.MM.YY]
    // Blockchain Write Date: [UNIX Date Generated by Smart Contract]
    // MD5 Hash: [MD5_hash]

    struct FileOutput {
		string separator;
        string file_number;
		string title;
		string album;
		string website;
		string ipfs_hash;
		string comment;
		string copyright;
        string submission_date;
		string blockchain_date;
        string md_hash;
    }

    struct FileOutputCollection {
		bytes32[] separator;
        bytes32[] file_number;
		bytes32[] title;
		bytes32[] album;
		bytes32[] website;
		bytes32[] ipfs_hash;
		bytes32[] comment;
		bytes32[] copyright;
        bytes32[] submission_date;
		bytes32[] blockchain_date;
        bytes32[] md_hash;
    }

    uint256 private size;

	// Searches will be done nased on IPFS hash and SHA256 Hash.

    mapping(uint256 => bytes32) filesNumberIndex;
    mapping(bytes32 => uint256[]) filesByNumber;

    mapping(uint256 => bytes32) filesIpfsHashIndex;
    mapping(bytes32 => uint256[]) filesByIpfsHash;

	mapping(uint256 => bytes32) filesMDHashIndex;
    mapping(bytes32 => uint256[]) filesByMDHash;

  
	mapping(uint256 => bytes32) filesTitleIndex;
    mapping(uint256 => bytes32) filesAlbumSeriesIndex;
	mapping(uint256 => bytes32) filesWebsiteIndex;
	mapping(uint256 => bytes32) filesCommentIndex;
	mapping(uint256 => bytes32) filesCopyrightIndex;
    mapping(uint256 => bytes32) filesSubmissionDateIndex;
	mapping(uint256 => uint256) filesBlockchainDateIndex;
    
    function initialize() initializer public {
        __Ownable_init();
    }

    function addFile(string[] memory metadata) public onlyOwner returns (uint256) {

        require( metadata.length == 9);

        // data validation : String must be convertable to bytes32
        require(dataValidate(metadata[0]));
        require(dataValidate(metadata[1]));
        require(dataValidate(metadata[2]));
        require(dataValidate(metadata[3]));
        require(dataValidate(metadata[4]));
        require(dataValidate(metadata[5]));
        require(dataValidate(metadata[6]));
        require(dataValidate(metadata[7]));
        require(dataValidate(metadata[8]));

		// Data is pasted in FileOutput Order. Blockchain date is skipped because it will be added when the block is mined.
		// 8 Items in total

        bytes32 _file_number = dataConvert(metadata[0]);
        bytes32 _title = dataConvert(metadata[1]);
        bytes32 _album = dataConvert(metadata[2]);
        bytes32 _website = dataConvert(metadata[3]);
	    bytes32 _ipfs_hash = dataConvert(metadata[4]);
        bytes32 _comment = dataConvert(metadata[5]);
		bytes32 _copyright = dataConvert(metadata[6]);
        bytes32 _submission_date = dataConvert(metadata[7]);
		bytes32 _md_hash = dataConvert(metadata[8]);
 

        filesNumberIndex[size] = _file_number;
        filesTitleIndex[size] = _title;
        filesAlbumSeriesIndex[size] = _album;
        filesWebsiteIndex[size] = _website;
        filesIpfsHashIndex[size] = _ipfs_hash;
        filesCommentIndex[size] = _comment;
        filesCopyrightIndex[size] = _copyright;
        filesSubmissionDateIndex[size] = _submission_date;
        filesBlockchainDateIndex[size] = block.timestamp;
		filesMDHashIndex[size] = _md_hash;


        filesByNumber[_file_number].push(size);
        filesByIpfsHash[_ipfs_hash].push(size);
        filesByMDHash[_md_hash].push(size);

        size = size + 1;
        return size;
    }

    function Find_Files_by_QI_Audio_Catalogue_Number(string calldata QI_Audio_Catalogue) view external returns (FileOutput[] memory) {
        require(dataValidate(QI_Audio_Catalogue));
        return findFilesByKey(1, dataConvert(QI_Audio_Catalogue));
    }

    function Find_Files_by_IPFS_Hash(string calldata IPFS_Hash) view external returns (FileOutput[] memory) {
        require(dataValidate(IPFS_Hash));
        return findFilesByKey(2, dataConvert(IPFS_Hash));
    }

    function Find_Files_by_MD5_Hash(string calldata MD5_Hash) view external returns (FileOutput[] memory) {
        require(dataValidate(MD5_Hash));
        return findFilesByKey(3, dataConvert(MD5_Hash));
    }

    function findFilesByKey(int key, bytes32 hash) view internal returns (FileOutput[] memory) {
        uint256 len;


        if(key == 1){
            len = filesByNumber[hash].length;
        } 

        if(key == 2){
            len = filesByIpfsHash[hash].length;
        } 

        if(key == 3){
            len = filesByMDHash[hash].length;
        } 

        FileOutputCollection memory outputsCollection;

        outputsCollection.separator = new bytes32[](len);
        outputsCollection.file_number = new bytes32[](len);
        outputsCollection.title = new bytes32[](len);
        outputsCollection.album = new bytes32[](len);
        outputsCollection.website = new bytes32[](len);
        outputsCollection.ipfs_hash = new bytes32[](len);
        outputsCollection.comment = new bytes32[](len);
        outputsCollection.copyright = new bytes32[](len);
        outputsCollection.submission_date = new bytes32[](len);
        outputsCollection.blockchain_date = new bytes32[](len);	
		outputsCollection.md_hash = new bytes32[](len);	

        for (uint256 index = 0; index < len; index++){
            uint256 id;

            if(key == 1){
                id = filesByNumber[hash][index];
            } 

            if(key == 2){
                id = filesByIpfsHash[hash][index];
            } 

            if(key == 3){
                id = filesByMDHash[hash][index];
            } 

            (uint year, uint month, uint day) = timestampToDate(filesBlockchainDateIndex[id]);

            outputsCollection.file_number[index] = filesNumberIndex[id];
            outputsCollection.title[index] = filesTitleIndex[id];
            outputsCollection.album[index] = filesAlbumSeriesIndex[id];
            outputsCollection.website[index] = filesWebsiteIndex[id];
            outputsCollection.ipfs_hash[index] = filesIpfsHashIndex[id];
            outputsCollection.comment[index] = filesCommentIndex[id];
            outputsCollection.copyright[index] = filesCopyrightIndex[id];
            outputsCollection.submission_date[index] = filesSubmissionDateIndex[id];
            outputsCollection.blockchain_date[index] =  concat( _convertVaalue(day),  ".",  _convertVaalue(month), ".", _convertVaalue(year) );
            outputsCollection.md_hash[index] = filesMDHashIndex[id];	

        }

        
		FileOutput[] memory outputs = new FileOutput[](len);
		for (uint256 index = 0; index < len; index++) {

            FileOutput memory output;

            output = FileOutput(
                "****",
                concatOutput("File Number: ", dataOutput(outputsCollection.file_number[index])),
                concatOutput("Title: ", dataOutput(outputsCollection.title[index])),
                concatOutput("Series: ", dataOutput(outputsCollection.album[index])),
                concatOutput("Website: ", dataOutput(outputsCollection.website[index])),
                concatOutput("IPFS URL: https://ipfs.io/ipfs/", dataOutput(outputsCollection.ipfs_hash[index])),
                concatOutput("Comment: ", dataOutput(outputsCollection.comment[index])),
                concatOutput("Copyright: ", dataOutput(outputsCollection.copyright[index])),
                concatOutput("Submission Date: ", dataOutput(outputsCollection.submission_date[index])),
                concatOutput("Blockchain Write Date: ", dataOutput(outputsCollection.blockchain_date[index])),
                concatOutput("MD5 Hash: ", dataOutput(outputsCollection.md_hash[index]))
            );

			outputs[index] = output;
		}
		return outputs;

	}

	function concat(bytes32 a, bytes32 b) private pure returns (bytes32 value) {
        bytes memory _value = abi.encodePacked(a, b);
        assembly {
            value := mload(add(_value, 32))
        }
	}

    
	function timestampToDate(uint timestamp) internal pure returns (uint year, uint month, uint day) {
        (year, month, day) = _daysToDate(timestamp / (24 * 60 * 60));
    }


    function _convertVaalue(uint _value) internal pure returns (bytes32 value) {
        bytes memory result;
        if( _value <10) {
            result = abi.encodePacked("0", _value);
        } else {
            result = abi.encodePacked(_value);
        }
        assembly {
            value := mload(add(result, 32))
        }
    }

    function _daysToDate(uint _days) internal pure returns (uint year, uint month, uint day) {
        int __days = int(_days);

        int L = __days + 68569 + 2440588;
        int N = 4 * L / 146097;
        L = L - (146097 * N + 3) / 4;
        int _year = 4000 * (L + 1) / 1461001;
        L = L - 1461 * _year / 4 + 31;
        int _month = 80 * L / 2447;
        int _day = L - 2447 * _month / 80;
        L = _month / 11;
        _month = _month + 2 - 12 * L;
        _year = 100 * (N - 49) + _year + L;
        _year = _year % 100;

        year = uint(_year);
        month = uint(_month);
        day = uint(_day);
    }

	function concat(bytes32  a, bytes32  b, bytes32 c, bytes32 d, bytes32 e) private pure returns (bytes32 value) {
		bytes memory _value = abi.encodePacked(a, b, c, d, e);
        assembly {
            value := mload(add(_value, 32))
        }
	}

	function concatOutput(string memory a, string memory b) private pure returns (string memory) {
		return string(abi.encodePacked(a, b));
	}
    
    function dataConvert(string memory str) private pure returns (bytes32 value){
        assembly {
            value := mload(add(str, 32))
        }     
    }

    function dataOutput(bytes32 c) private pure returns (string memory value){
        value = string(abi.encodePacked(c));
    }

    function dataValidate(string memory str) private pure returns (bool value){
        if (bytes(str).length <= 32) {
            value = true ;
        } else  {
            value = false;
        }
    }

}