// SPDX-License-Identifier: MIT OR Apache-2.0

pragma solidity ^0.7.0;

import "@openzeppelin/contracts-upgradeable/proxy/Initializable.sol";

import "./mixins/roles/AdminRole.sol";
import "./mixins/CollateralManagement.sol";
import "./mixins/WithdrawFromEscrow.sol";

/**
 * @notice The Foundation treasury which collects fees generated by the market.
 * @dev The core responsibilities of this contract are collecting fees and whitelisting creators.
 */
contract FoundationTreasury is AdminRole, CollateralManagement, WithdrawFromEscrow {
  function initialize(address admin) public initializer {
    AdminRole._initializeAdminRole(admin);
  }
}